fix(EMS-618): Heading href link
UK-Export-Finance/exip pull request #171
Opened 2022-12-05 15:50 UTC by Zainzzkk

# Issue: 
* Heading href didn't link to the right page.
* On insurance pages, was going to quote start
* All pages did not have functioning href on heading

# Changes made:
* Added to core and single page variables so href is on every page
* Linked href to insurance start for insurance pages
* Updated unit tests
* Added to e2e tests to test href

2022-12-05 15:54 UTC, ttbarnes commented on src/ui/types/page-variables.d.ts
> +  START_ROUTE?: string;
Should `START_ROUTE` be required?

2022-12-05 16:01 UTC, Zainzzkk commented on src/ui/types/page-variables.d.ts
> +  START_ROUTE?: string;
fixed

2022-12-05 16:51 UTC, abhi-markan requested changes
All looks good, apart from comments mentioned by @ttbarnes

2022-12-07 10:06 UTC, Zainzzkk commented on src/ui/server/middleware/required-data-provided/quote/index.ts
> +  const irrelevantRoutes = [BUYER_COUNTRY, CANNOT_APPLY, GET_A_QUOTE_BY_EMAIL, NEED_TO_START_AGAIN, START];
done - no e2e test needed

2022-12-07 14:00 UTC, ttbarnes approved these changes

2022-12-07 14:04 UTC, ttbarnes approved these changes

2022-12-07 14:46 UTC, abhi-markan approved these changes

2022-12-07 14:47 UTC, abhi-markan requested changes
Failing test, please address.

2022-12-07 15:11 UTC, merged