chore(deps): Bump dependencies
UK-Export-Finance/exip pull request #2310
Opened 2024-04-23 16:15 UTC by ttbarnes

## Introduction :pencil2:
- Dependabot flagged some dependency updates.

## Resolution :heavy_check_mark:
- Update dependencies.

2024-04-23 16:36 UTC, ttbarnes commented on package.json
>      "@keystone-6/fields-document": "^8.0.2",
Need to bump `@keystone-6/fields-document`

2024-04-24 07:15 UTC, abhi-markan requested changes

2024-04-24 09:04 UTC, ttbarnes commented on src/api/schema.graphql
> -  authenticateUserWithPassword(email: String!, password: String!): UserAuthenticationWithPasswordResult
No 😢

2024-04-24 09:26 UTC, ttbarnes commented on src/api/schema.graphql
> -  authenticateUserWithPassword(email: String!, password: String!): UserAuthenticationWithPasswordResult
There is some issue with the latest keystone package versions - have created an issue. Will revert some package changes in the meantime.

2024-04-26 11:15 UTC, abhi-markan approved these changes

2024-04-26 11:43 UTC, merged