fix(EMS-990): Company Details - Turnover - Allow negative turnover
UK-Export-Finance/exip pull request #315
Opened 2023-02-13 16:34 UTC by Zainzzkk

# Issue:
* estimatedTurnover did not allow values below 0

# Changes made:
* Added optional allowNegativeValue variable to wholeNumberValidation.  If set to true, then will allow numbers below 0
* Updated validation for estimate-annual-turnover to set flag to true
* Updated tests

2023-02-13 16:39 UTC, abhi-markan commented on src/ui/server/helpers/whole-number-validation/index.ts
> + * @param {Boolean} allowNegativeValue optional field set to false which allows for negative numbers below 0
Please replace to `false as default, if false then allows for negative numbers below 0.`

2023-02-13 16:42 UTC, abhi-markan requested changes
Looks good to me, please address the comments.

2023-02-13 16:42 UTC, abhi-markan commented on src/ui/server/helpers/whole-number-validation/index.ts
> + * if allowNegativeNumbers is set to true, then will return validation error if number below 0
Please add full stop at end so it is easier to read.

2023-02-13 16:42 UTC, abhi-markan commented on src/ui/server/helpers/whole-number-validation/index.test.ts
> +    it('should not return a validation error', () => {
Please add a number with decimals `-3.123` and one with `-3.AB123`. Thanks

2023-02-13 16:42 UTC, abhi-markan commented on e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
> +    it('should not display validation errors', () => {
Please add a test case with decimals `-256.123`.

2023-02-13 17:13 UTC, ttbarnes commented on src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
> +  const allowNegativeValue = true;
Very minor and not a blocker but can we add a space between these 3 const's so it's easier to read

2023-02-13 17:36 UTC, ttbarnes approved these changes

2023-02-14 11:47 UTC, abhi-markan approved these changes

2023-02-14 11:47 UTC, merged