feat(EMS-921-1217): Application submission
UK-Export-Finance/exip pull request #399
Opened 2023-03-27 15:33 UTC by ttbarnes

⚠️ Need these 2 PRs merged first:
- https://github.com/UK-Export-Finance/exip/pull/396
- https://github.com/UK-Export-Finance/exip/pull/397

This PR adds the application submission functionality.

# Changes
- Setup new GQL resolver, `submitApplication`. This function changes the application status to submitted, adds a submission date and (new field) `previousStatus` for future iterations/integrations.
- Update the declarations "how your data will be used" POST controller to call the submit application GQL mutation.
- Setup route, controller and page for the "application submitted" page.

## TODO
- Design and copy tweaks for the submission page.

2023-03-28 21:52 UTC, abhi-markan requested changes
Overall looks good, few comments to address please.

2023-03-28 21:52 UTC, abhi-markan commented on e2e-tests/cypress/support/insurance/complete-sign-in-and-submit-an-application.js
> + * completeSignInAndSubmitAnApplication
One line function explanation please.

2023-03-28 21:52 UTC, abhi-markan commented on src/api/custom-resolvers/submit-application.ts
> + * submitApplication
Same as above please.

2023-03-28 21:52 UTC, abhi-markan commented on src/api/custom-resolvers/submit-application.ts
> +      console.info('Unable to submit application - application already submitted');
Should this be `console.error`?

2023-03-28 21:52 UTC, abhi-markan commented on src/api/custom-resolvers/submit-application.ts
> +    console.info('Unable to submit application - no application found');
Should this be `console.error`?

2023-03-28 21:52 UTC, abhi-markan commented on src/ui/styles/styles.scss
> +  max-width: 360px;
Where has this value been derived from please?

2023-03-29 08:17 UTC, ttbarnes commented on src/api/custom-resolvers/submit-application.ts
> +      console.info('Unable to submit application - application already submitted');
Good shout, updated

2023-03-29 08:47 UTC, abhi-markan approved these changes

2023-03-29 08:51 UTC, merged